apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-front
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp

    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          resources:
              limits:
                memory: 128Mi
                cpu: 128m
  replicas: 3
  selector:
    matchLabels:
      app: myapp